var greeting = "";
var greeting = 'Hello, everybody!';
var specialGuest = "Neil deGrasse Tyson"
var specialGuest = "Neil deGrasse Tyson";
var greetSpecialGuest = "" + specialGuest + "!";
var greetSpecialGuest = "Hello, everybody!', + "Neil deGrasse Tyson";
var topic = "space";
var topic = 'Let's talk about space.";
var conversation = `${topic}`;
var conversation = ${3+5};
